services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: redrob
      POSTGRES_PASSWORD: redrob_dev_password
      POSTGRES_DB: redrob_hrms
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
